### PR TITLE
Unpin numpy

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@conda-forge/core could someone merge this ?

**Comment by mwcraig** [comment]
@jschueller — could you please bump the build number?

**Comment by jschueller** [comment]
@mwcraig, right, done

**Comment by mwcraig** [comment]
Merging, since travis passed earlier....

**Pull request merged**
