### PR TITLE
Rebuild numpy2 0 1 h7f71f9

### PR DESCRIPTION
**Pull request by maxnoe**
I rebased the bot and re-rendered.

This should correctly build for numpy 2.0 (now first for 1.1) which should then also work for 1.2

### CODE REVIEW

**Comment by maxnoe** [comment]
The issue here is that there isn't an astropy version for python 3.9 that is compatible with numpy 2.0.

What shall we do? I am not sure how to hack the build config to use the older numpy on 3.9.

Simplest would be to drop 3.9 and require 3.10+

**Comment by maxnoe** [comment]
Any idea why numpy 1.26 fails to import on the ppc and arm platforms under 3.9?

**Comment by mwcraig** [comment]
Maybe -- right now the selector for that case requires `numpy >=1.25` so I think it is installing `numpy 2` in some parts of the build. See [this line, where numpy 1.25 is installed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=985866&view=logs&j=abc074f0-60c0-536a-336f-04e4d67bf687&t=3f1a5a38-941c-50df-03bc-17c577e527bb&l=622) and [this line, where numpy 2.0 is installed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=985866&view=logs&j=abc074f0-60c0-536a-336f-04e4d67bf687&t=3f1a5a38-941c-50df-03bc-17c577e527bb&l=699).

I'll try a variation or two on the selectors to more firmly pin numpy for python 3.9. If that doesn't work then I think it makes sense to just drop the python 3.9 build. Folks are welcome to compile on their own if they really need that combination.

**Comment by maxnoe** [comment]
Ah, good catch! Seems to have worked

**Comment by mwcraig** [comment]
Thanks for getting it down to an issue I could fix!

**Pull request merged**
