### PR TITLE
astropscrppy 1.2.0

### PR DESCRIPTION
**Pull request by mwcraig**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #36

### CODE REVIEW

**Comment by mwcraig** [comment]
@conda-forge-admin please rerender

**Comment by mwcraig** [comment]
Any ideas, @maxnoe?

**Comment by maxnoe** [comment]
I think we are missing the numpy 2 migration parts of #37, the numpy versions installed to build are mich older

**Comment by maxnoe** [comment]
I rebased the bot branch and opened a PR here: https://github.com/conda-forge/astroscrappy-feedstock/pull/41

**Comment by mwcraig** [comment]
@conda-forge-admin please rerender

**Comment by mwcraig** [comment]
@conda-forge-admin please rerender

**Comment by mwcraig** [comment]
The remaining failures are because `astroscrappy.pyx` isn't being cythonized on python 3.9. For Python >=3.10 cythonization happens (even though `astroscrappy.c` is present in the source distribution) because it depends on numpy's `numpy/__init__.cython-30.pxd` ([see this line in the `osx` build for `3.10`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=986052&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=1150)).

I'm going to try to write a patch to delete `astroscrappy.c`...a little tougher because it is in `.gitignore`. If that does work I'll try modifying the build script.

**Comment by mwcraig** [comment]
@conda-forge-admin please rerender

**Comment by mwcraig** [comment]
🎉All lights are green so I'm merging this

**Pull request merged**
